### ISSUE TITLE
Installation fails - status set to notworking in one week

### ISSUE THREAD

**Issue by JimboJoe** [YunoHost-Apps/phpldapadmin_ynh#2]
Hello,

Your app failed to install on our CI, hence it will be set at notworking status in one week unless installation is fixed.

You can find the complete log here
https://ci-apps.yunohost.org/jenkins/job/phpldapadmin%20(Community)/6/consoleFull

Don't hesitate to join our Apps packaging room on XMPP (apps@conference.yunohost.org) for help!

The YunoHost Apps Group

**Comment by aymhce** [comment]
Hello @JimboJoe since e990a93, can you retry CI please  ?

**Comment by aymhce** [comment]
e990a93

**Comment by aymhce** [comment]
ref https://github.com/YunoHost/apps/pull/326

**Comment by JimboJoe** [comment]
package_check still fails installation for me... I think you need to rename your `check_process.default` in `check_process` and adapt it a little bit. Did you test locally with package_check?

**Comment by aymhce** [comment]
ok, I have fill it on last commit 3965ae8d51f181b54906fc140350b48c0763d94b
(I can't test at home, lxc don't work ...)

**Comment by JimboJoe** [comment]
Sorry for the delay. I've tested and it does indeed work much better now! 👍
